FROM apache/airflow:2.8.1-python3.10

USER root

# Instala as libs necessárias
RUN pip install --no-cache-dir \
    pandas \
    snowflake-connector-python \
    sqlalchemy \
    apache-airflow-providers-snowflake

USER airflow
